### ISSUE TITLE
닷컴 (.com) 주소 어디서 구함

### ISSUE THREAD

**Issue by 1top10000** [entchzh/-entchzh.github.io#1]
.com 산거죠?

**Comment by entchzh** [comment]
산거없는데요?

**Comment by 1top10000** [comment]
아 그런가요... 넵!

**Comment by entchzh** [comment]
몰라요 아무거나 누르고 다녔는데.. 진짜 모름

2024년 4월 30일 (화) 오후 8:05, 1top10000 ***@***.***>님이 작성:

**Comment by 1top10000** [comment]
limchat.com 이거용 뭐.. 그런건 없나보군용 사거나... 뭐 그런거요...

**Comment by entchzh** [comment]
방금 뭐 보냐신건가요?

2024년 7월 24일 (수) 오전 11:50, 1top10000 ***@***.***>님이 작성:

**Comment by 1top10000** [comment]
? 뭔가 한거 없음(??)
